### ISSUE TITLE
Unable to complete delivery process

### ISSUE THREAD

**Issue by francesca-gigante** [IBM/chatbot-deployer#28]
The created toolchain has a delivery pipeline with no stage.
I tried to get different chatbot on my IBM cloud. 

![issue_toolchain](https://user-images.githubusercontent.com/14333369/36786772-e7620096-1c87-11e8-8d40-16c0c120c03f.png)

**Comment by stevemar** [comment]
I am also seeing this, I asked in the #devops-pipeline-core internal slack channel for guidance. Something must have changed in the devops service that is causing our current implementation to break.

**Comment by stevemar** [comment]
I believe this was opened just before index and was resolved in time. I can't recall the exact solution but I believe it was an error with the toolchain team or a byproduct of the Watson assistant rename.
